parameters:
    kilix_api_core.api_paramaters_listener.class: Kilix\Bundle\ApiCoreBundle\EventListener\ApiParametersListener

services:
    kilix_api_core.example:
        class: %kilix_api_core.api_paramaters_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
