parameters:
    kilix_api_core.api_paramaters_listener.class: Kilix\Bundle\ApiCoreBundle\EventListener\ApiParametersListener
    kilix_api_core.blueprint_manager.class: Kilix\Bundle\ApiCoreBundle\Tools\BlueprintManager

services:
    kilix_api_core.blueprint_manager:
        class: %kilix_api_core.blueprint_manager.class%
        arguments:
            - @kernel
            - %kilix_api_core.aglio_bin%
            - %kilix_api_core.blueprint_parser_bin%
            - %kilix_api_core.apiary2postman_bin%
            - %kilix_api_core.blueman_bin%
            - %kilix_api_core.default_postman_converter%

    kilix_api_core.api_paramaters_listener:
        class: %kilix_api_core.api_paramaters_listener.class%
        arguments: [@annotation_reader, @validator]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    kilix_api_core.decoder_provider:
        class: Kilix\Bundle\ApiCoreBundle\Decoder\DecoderProvider
        arguments: [%kilix_api_core.decoders%]
        calls:
            - [setContainer, [@service_container]]

    kilix_api_core.decoder.json:
        class: Kilix\Bundle\ApiCoreBundle\Decoder\JsonDecoder

    kilix_api_core.content_type_listener:
        class: Kilix\Bundle\ApiCoreBundle\EventListener\ContentTypeListener
        arguments: [@kilix_api_core.decoder_provider]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
