---
before_script:
  # - whoami
  # - id -u $(whoami)
  - docker info
  # - docker version
  - docker-compose version

build_image:
  script:
    - docker-compose build

test:
  script:
    - mkdir -p vendor
    - mkdir -p Tests/Fixtures/web
    - mkdir -p Tests/Tools/Fixtures/doc
    - setfacl -R -m u:"$(whoami)":rwX vendor && setfacl -R -dm u:"$(whoami)":rwX vendor
    - setfacl -R -m u:"$(whoami)":rwX Tests/Fixtures/web && setfacl -R -dm u:"$(whoami)":rwX Tests/Fixtures/web
    - setfacl -R -m u:"$(whoami)":rwX Tests/Tools/Fixtures/doc && setfacl -R -dm u:"$(whoami)":rwX Tests/Tools/Fixtures/doc
    # - docker-compose run --rm -e GITHUB_API_TOKEN=  php make install test
    - docker-compose run --rm php make install test
