php:
    build: dockerfiles/php
    container_name: apicore_test
    volumes:
        - "./:/srv/api-core-bundle"
    environment:
        SSH_PRIVATE_KEY:
        SSH_PUBLIC_KEY:
        GITHUB_API_TOKEN:
        GROUP_ID: 1000
        USER_ID: 1000
        GROUPNAME: dev
        USERNAME: dev
        HOMEDIR: /home/dev
